### ISSUE TITLE
エンドポイントの変更とヘッダーの設定

### ISSUE THREAD

**Issue by TakuroSugahara** [TakuroSugahara/graphql-client-vim#9]
- dbuiを参考にtree表示で自前で持っているエンドポイントごとの一覧を作成
- エンドポイントの名前を表示
- enterとかopenコマンドとかを実行したらそのエンドポイントが設定されて実行できるようになる

**Comment by afrou04** [comment]
- [x] 独自の名前をkeyにheaderとendpointの設定を行えるようにする
  - [x] globalな変数を置いてそこで管理できる
- [x] ドロワーを表示してkeyの一覧が表示されるようにする
- [x] openコマンドを実行したら対象のkeyのendpoint, headerが設定されるようになる
